name: ACubelets
version: ${project.version}
main: me.davidml16.acubelets.Main
depend: [ProtocolLib]
softdepend: [PlaceholderAPI, Vault, Multiverse-Core, Hyperverse, HolographicDisplays]
authors: [DavidML16]
api-version: 1.13